apiVersion: v1
data:
  .dockerconfigjson: __ACR_SECRET__
kind: Secret
metadata:
  name: acrsecret
  selfLink: /api/v1/namespaces/default/secrets/acrsecret
  uid: 967b1963-2a08-49f2-9a8d-bfe79ca83d60
type: kubernetes.io/dockerconfigjson