- hosts: localhost
  gather_facts: false

  vars:
    app_name: "hello-python-service"
    aks_resource_group: "dev-terraform-rg"
    aks_cluster_name: "dev-aks-cluster-aks"

  tasks:
    - name:  Login to Azure and Connect to AKS CLuster
      shell: |
        az login --service-principal -u {{ AKS_SP_ID | quote }} -p {{ AKS_SP_SECRET | quote }} --tenant {{ TENANT_ID | quote }}
        az account set --subscription {{ SUBSCRIPTION_ID | quote }}
        az aks get-credentials --resource-group {{aks_resource_group}} --name {{aks_cluster_name}} --admin
      no_log: true

    - name: Get service ip address
      shell: |
        kubectl get svc {{app_name}} -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: kubectl_ip

    - name: Get service port
      shell: |
        kubectl get svc {{app_name}} -o jsonpath='{.spec.ports[0].port}'
      register: kubectl_port

    - set_fact:
        ip: "{{kubectl_ip.stdout}}"
        port: "{{kubectl_port.stdout}}"

    - name: Test Python app
      uri:
        url: http://{{ip}}:{{port}}
        status_code: 200
